version: 2

models:
  - name: gold_community_analytics
    description: Business-ready community analytics combining listings, crime, census, and schools
    columns:
      - name: community_area_number
        tests:
          - not_null
          - unique
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 77
      - name: community_area_name
        tests:
          - not_null
      - name: per_capita_income
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: hardship_index
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
      - name: total_listings
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: total_crime_incidents
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: total_schools
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: gold_real_estate_summary
    description: Real estate market summary and trends across categories
    columns:
      - name: summary_type
        tests:
          - accepted_values:
              values: [property_type_summary, price_range_summary, community_real_estate, year_built_trends]
      - name: total_properties
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: avg_list_price
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
